### ISSUE TITLE
A problem with the z-index in the demo 

### ISSUE THREAD

**Issue by Ahmed-Ayman** [drcmda/mauerwerk#2]
In the simplfied demo the text is appearing under the overlay while testing it on the mobile. Maybe we need to increase the z-index to handle it on the mobile

**Comment by drcmda** [comment]
Hi @Ahmed-Ayman 

oh that's a bummer. I do set z-index on the opening cells (or else other cells would cut into it), but perhaps it needs some deeper consideration. Which device are you using btw?

**Comment by drcmda** [comment]
Tried it on my iphone now, actually it looks alright to me, i mean - it looks horrible because the circle thing overlays the text beneath - but that's because i haven't made the demo responsive, there are no media queries, etc. Is it this problem you're seeing?

**Comment by Ahmed-Ayman** [comment]
Yep thats exactly what I was talking about and was thinking like we can handle it by setting a media query and a z-index for it on the mobile! 
And I'm using xiaomi redmi note 5 A.. Android 8

**Comment by drcmda** [comment]
The inner content is up to you, the demo just slaps a bunch of absolute divs onto it, i sized it more or less after codesandbox on desktop. I think we're fine :-)

**Comment by Ahmed-Ayman** [comment]
alright : )
I was just thinking like it it's gonna look more perfect this way, pardon my perfectionism! :'D
