### ISSUE TITLE
disable animation

### ISSUE THREAD

**Issue by nirsnappy** [drcmda/mauerwerk#8]
hi we want to disable animation on mobile,  transitionMount={false} didnt work for us.
any other options we miss ?

**Comment by drcmda** [comment]
It should be possible to give it a config with immediate set to true.

```jsx
<Grid config={{ immediate: true }} ... />
```

**Comment by nirsnappy** [comment]
thanks for the response.
amm i actually can't see the differences with it or without it .
any other ideas ? :)
(i can still see the animation of the grid items coming from left side to the screen)

**Comment by drcmda** [comment]
i was confused, immediate isn't part of the config, but the spring. the spring itself needs to get this property.

The easiest right now would probably to base on this https://codesandbox.io/s/26mjowzpr?from-embed and make your own rules. if you set immediate: true in there, it will work.

**Comment by drcmda** [comment]
Or make a quick PR if you need it here.
